// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// l2_norm
double l2_norm(NumericVector x);
RcppExport SEXP _matern32_l2_norm(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(l2_norm(x));
    return rcpp_result_gen;
END_RCPP
}
// na_matrix
NumericMatrix na_matrix(unsigned int n, unsigned int p);
RcppExport SEXP _matern32_na_matrix(SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(na_matrix(n, p));
    return rcpp_result_gen;
END_RCPP
}
// weighted_l2_norm
double weighted_l2_norm(NumericVector x, NumericVector l);
RcppExport SEXP _matern32_weighted_l2_norm(SEXP xSEXP, SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_l2_norm(x, l));
    return rcpp_result_gen;
END_RCPP
}
// matern32_kxx_cpp
NumericMatrix matern32_kxx_cpp(NumericMatrix x, NumericVector l);
RcppExport SEXP _matern32_matern32_kxx_cpp(SEXP xSEXP, SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(matern32_kxx_cpp(x, l));
    return rcpp_result_gen;
END_RCPP
}
// matern32_kxstar_cpp
NumericMatrix matern32_kxstar_cpp(NumericMatrix newx, NumericMatrix x, NumericVector l);
RcppExport SEXP _matern32_matern32_kxstar_cpp(SEXP newxSEXP, SEXP xSEXP, SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type newx(newxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(matern32_kxstar_cpp(newx, x, l));
    return rcpp_result_gen;
END_RCPP
}
// derivs
List derivs(NumericMatrix x, NumericVector c, double l);
RcppExport SEXP _matern32_derivs(SEXP xSEXP, SEXP cSEXP, SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(derivs(x, c, l));
    return rcpp_result_gen;
END_RCPP
}
// inters
NumericVector inters(NumericMatrix x, NumericVector c, unsigned long int i0, double l);
RcppExport SEXP _matern32_inters(SEXP xSEXP, SEXP cSEXP, SEXP i0SEXP, SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< unsigned long int >::type i0(i0SEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(inters(x, c, i0, l));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _matern32_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_matern32_l2_norm", (DL_FUNC) &_matern32_l2_norm, 1},
    {"_matern32_na_matrix", (DL_FUNC) &_matern32_na_matrix, 2},
    {"_matern32_weighted_l2_norm", (DL_FUNC) &_matern32_weighted_l2_norm, 2},
    {"_matern32_matern32_kxx_cpp", (DL_FUNC) &_matern32_matern32_kxx_cpp, 2},
    {"_matern32_matern32_kxstar_cpp", (DL_FUNC) &_matern32_matern32_kxstar_cpp, 3},
    {"_matern32_derivs", (DL_FUNC) &_matern32_derivs, 3},
    {"_matern32_inters", (DL_FUNC) &_matern32_inters, 4},
    {"_matern32_rcpp_hello_world", (DL_FUNC) &_matern32_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_matern32(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
