# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

l2_norm <- function(x) {
    .Call('_matern32_l2_norm', PACKAGE = 'matern32', x)
}

na_matrix <- function(n, p) {
    .Call('_matern32_na_matrix', PACKAGE = 'matern32', n, p)
}

weighted_l2_norm <- function(x, l) {
    .Call('_matern32_weighted_l2_norm', PACKAGE = 'matern32', x, l)
}

matern32_kxx_cpp <- function(x, sigma, l) {
    .Call('_matern32_matern32_kxx_cpp', PACKAGE = 'matern32', x, sigma, l)
}

matern32_kxstar_cpp <- function(newx, x, sigma, l) {
    .Call('_matern32_matern32_kxstar_cpp', PACKAGE = 'matern32', newx, x, sigma, l)
}

derivs <- function(x, c, sigma, l) {
    .Call('_matern32_derivs', PACKAGE = 'matern32', x, c, sigma, l)
}

inters <- function(x, c, i0, sigma, l) {
    .Call('_matern32_inters', PACKAGE = 'matern32', x, c, i0, sigma, l)
}

rcpp_hello_world <- function() {
    .Call('_matern32_rcpp_hello_world', PACKAGE = 'matern32')
}

