# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crossprod_cpp <- function(x, y) {
    .Call('_matern32_crossprod_cpp', PACKAGE = 'matern32', x, y)
}

l2_norm <- function(x) {
    .Call('_matern32_l2_norm', PACKAGE = 'matern32', x)
}

na_matrix <- function(n, p) {
    .Call('_matern32_na_matrix', PACKAGE = 'matern32', n, p)
}

weighted_l2_norm <- function(x, l) {
    .Call('_matern32_weighted_l2_norm', PACKAGE = 'matern32', x, l)
}

matern32_kxx_cpp <- function(x, l) {
    .Call('_matern32_matern32_kxx_cpp', PACKAGE = 'matern32', x, l)
}

matern32_kxstar_cpp <- function(newx, x, l) {
    .Call('_matern32_matern32_kxstar_cpp', PACKAGE = 'matern32', newx, x, l)
}

derivs <- function(x, c, l) {
    .Call('_matern32_derivs', PACKAGE = 'matern32', x, c, l)
}

inters <- function(x, j1, j2, c, l) {
    .Call('_matern32_inters', PACKAGE = 'matern32', x, j1, j2, c, l)
}

inters2 <- function(x, j1, j2, c, l) {
    .Call('_matern32_inters2', PACKAGE = 'matern32', x, j1, j2, c, l)
}

solve_eigen <- function(Eigenvectors, Eigenvalues, y, lambda) {
    .Call('_matern32_solve_eigen', PACKAGE = 'matern32', Eigenvectors, Eigenvalues, y, lambda)
}

find_lam_eigen <- function(Eigenvectors, Eigenvalues, y, lambda_vector) {
    .Call('_matern32_find_lam_eigen', PACKAGE = 'matern32', Eigenvectors, Eigenvalues, y, lambda_vector)
}

